### ISSUE TITLE
No Address for specific system routines

### ISSUE THREAD

**Issue by 0xGREG** [everdox/InfinityHook#10]
Hey everyone, do you guys have any idea why routines with no _In_ or _Out_ don't have pointers?

Eg.: `NtQueryMultipleValueKey`

Edit: Any way to hook those although they are not in ntoskrnl?

Thanks.

**Comment by JutGreg** [comment]
Nevermind, they are not in ntoskrnl

**Comment by BerkanYildiz** [comment]
What do you mean by "_don't have pointers_" ?
It does have "_pointers_"..

```c
__kernel_entry NTSTATUS NtQueryMultipleValueKey(
  HANDLE			KeyHandle,
  IN PKEY_VALUE_ENTRY		ValueEntries,
  ULONG				EntryCount,
  OUT PVOID			ValueBuffer,
  IN OUT PULONG			BufferLength,
  OPTIONAL OUT PULONG           RequiredBufferLength
);
```

Here, I added the "IN, OUT, OPTIONAL" for you.

**Comment by niallnsec** [comment]
If the symbol you are looking for is not exported by the kernel, you should still be able to hook it using the SyscallIndex number and looking up the function pointer in the kernels syscall table instead of using MmGetSystemRoutineAddress.

You will have to work out the current version of the kernel first so you know which indices to use. There is a useful reference source here: https://j00ru.vexillium.org/syscalls/nt/64/ (64-bit) and https://j00ru.vexillium.org/syscalls/nt/32/ (32-bit)
