### ISSUE TITLE
off-by-one error

### ISSUE THREAD

**Issue by milabs** [everdox/InfinityHook#2]
https://github.com/everdox/InfinityHook/blob/b4ee7cf37ba584b74bbbbfd8bcb1b3652b2ce3c4/src/libinfinityhook/mm.cpp#L37

`for (size_t i = 0; i < (SizeOfBuffer - SizeOfSignature); ++i)`
should be
`for (size_t i = 0; i < (SizeOfBuffer - SizeOfSignature) + 1; ++i)`

**Comment by Ch40zz** [comment]
Uhm no?
If you subtract a size from a size its still a size - and sizes are always indexed starting by 0 and therefore using the smaller (<) operator.
Your code is actually reading 1 byte too far.

< SizeOfBuffer would exactly read SizeOfBuffer bytes, therefore we subtract the exact pattern length.

**Comment by brymko** [comment]
allow me to elaborate:
lets say we have a buffer of size 0x10 and a signature of size 4 with the signature being 0xdeadbeef in (big endian)
the buffer can look like this:^
```
00 11 22 33 | 44 55 66 77 | 88 99 AA BB | DE AD BE EF
```
we subtract 4 from 16 therefore looping 12 times

from the code we can deduct that in the last iteration memcpy gets calling with i = 11 aka refering to the BB byte
```
00 11 22 33 | 44 55 66 77 | 88 99 AA BB | DE AD BE EF
                                     ^^^^^^^^^^^^^
```
because this is in the last iteration the signature is never found.

edit: styling

**Comment by Ch40zz** [comment]
Uh lmao thats right, looks like I fucked something up while going through that :P
Thanks for the example, next time I should actually go through an example!

**Comment by nmulasmajic** [comment]
Fixed in the latest commit. Thanks for reporting.
