### ISSUE TITLE
can it hook Mm function?

### ISSUE THREAD

**Issue by YangKi1902** [everdox/InfinityHook#4]
hello, will it able to hook Mm functions ? what's the code i need to change ?

**Comment by BerkanYildiz** [comment]
Yes it is possible to do that. You have to replace the used function name :
https://github.com/everdox/InfinityHook/blob/b4ee7cf37ba584b74bbbbfd8bcb1b3652b2ce3c4/src/kinfinityhook/entry.cpp#L23

Instead of "_NtCreateFile_", you're going to put your "_MmXxx_" function name, for example, "_MmCopyVirtualMemory_".

Then correctly setup your detour function, and you should be done.

**Comment by Ch40zz** [comment]
No, not with the current code, it only triggers in KiSystemCall64 which only gets called for syscalls.

**Comment by YangKi1902** [comment]
> Yes it is possible to do that. You have to replace the used function name :
> https://github.com/everdox/InfinityHook/blob/b4ee7cf37ba584b74bbbbfd8bcb1b3652b2ce3c4/src/kinfinityhook/entry.cpp#L23
> 
> Instead of "_NtCreateFile_", you're going to put your "_MmXxx_" function name, for example, "_MmCopyVirtualMemory_".
> 
> Then correctly setup your detour function, and you should be done.

well i think not easy like that, we need to change event trace class and do something more maybe.

**Comment by BerkanYildiz** [comment]
Actually no, as @Ch40zz, it's for usermode syscalls only.

https://github.com/everdox/InfinityHook/blob/b4ee7cf37ba584b74bbbbfd8bcb1b3652b2ce3c4/src/kinfinityhook/entry.cpp#L88
